# Generated by Django 5.0.7 on 2024-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('K', 'Kids'), ('WW', 'Womens Wear'), ('MW', 'Mens Wear')], max_length=2),
        ),
    ]
